main: dev.risas.lunarutils.LunarUtils
name: LunarUtils
version: 1.0.0-SNAPSHOT
author: Risas
commands:
  lunar:
    description: Main command of Lunar Utils
    aliases: [lunarutils, lunarclient, lunarclientutils, lcu, lu, lc]
  file:
    description: Reload all files
    aliases: [files]