main: dev.risas.lunarutils.LunarUtils
name: LunarUtils
version: 0.0.1-SNAPSHOT
author: Risas
commands:
  lunar:
    description: Main command of Lunar Utils
    aliases: [lunarutils, lunarclient, lunarclientutils, lcu, lu]
  file:
    description: Reload all files
    aliases: [files]